using EasyWallet.Business.Abstractions;
using EasyWallet.Business.Clients.Abstractions;
using EasyWallet.Business.Mapper;
using EasyWallet.Business.Models;
using EasyWallet.Data.Abstractions;
using EasyWallet.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EasyWallet.Business.Services
{
    public class CategoryService : ICategoryService
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly ICategoriesClient _categoriesClient;

        public CategoryService(IUnitOfWork unitOfWork, ICategoriesClient categoriesClient)
        {
            _unitOfWork = unitOfWork;
            _categoriesClient = categoriesClient;
        }

        public async Task<IEnumerable<Category>> GetActiveCategoriesByUser(int userId)
        {
            var categories = await _categoriesClient.GetCategoriesByUserId(userId);

            return BusinessMapper.Mapper.Map<IEnumerable<Category>>(categories);
        }

        public async Task<int> CreateCategory(int userId, string name, IEnumerable<Tag> tags)
        {
            return await _categoriesClient.CreateCategory(userId, name, tags.Select(t => t.Name).ToList());
        }

        public async Task<Category> GetActiveCategoryById(int id)
        {
            var category = await _categoriesClient.GetCategoryById(id);

            return BusinessMapper.Mapper.Map<Category>(category);
        }

        public async Task UpdateCategory(int categoryId, string name, IEnumerable<Tag> tags)
        {
            var categoryData = await _unitOfWork.Categories.GetActiveCategoryWithTagsById(categoryId);
            categoryData.Name = name;

            var userTags = await _unitOfWork.Tags.GetActiveTagsByUser(categoryData.UserId);

            var newTags = new List<TagData>();
            foreach(var formTag in tags)
            {
                bool duplicatesNonAutoGeneratedTag = userTags.Any(t => t.Name == formTag.Name && !t.IsAutoGenerated);

                if (!string.IsNullOrEmpty(formTag.Name) && !duplicatesNonAutoGeneratedTag)
                {
                    var autogeneratedTag = userTags.FirstOrDefault(t => t.Name == formTag.Name && t.IsAutoGenerated);
                    if (autogeneratedTag != null)
                        autogeneratedTag.DeletedAt = DateTime.UtcNow;

                    newTags.Add(new TagData()
                    {
                        CategoryId = categoryData.Id,
                        Name = formTag.Name,
                        CreatedAt = DateTime.UtcNow
                    });
                }
            }

            await _unitOfWork.Tags.AddRangeAsync(newTags);

            foreach(var categoryTag in categoryData.Tags)
            {
                if (!tags.Any(t => t.Name == categoryTag.Name))
                    categoryTag.DeletedAt = DateTime.UtcNow;
            }

            await _unitOfWork.CommitAsync();
        }

        public async Task DeleteCategory(int id)
        {
            var categoryData = await _unitOfWork.Categories.GetActiveCategoryWithTagsById(id);
            categoryData.DeletedAt = DateTime.UtcNow;

            foreach (var tag in categoryData.Tags)
                tag.DeletedAt = DateTime.UtcNow;

            await _unitOfWork.CommitAsync();
        }
    }
}
