using System;

namespace EasyWallet.Business.Clients.Dtos
{
    public class KeywordDto
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public bool IsAutoGenerated { get; set; }
        public DateTime CreatedAt { get; set; }
    }
}
