namespace EasyWallet.Business.Models
{
    public class Tag
    {
        public int Id { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public bool IsAutoGenerated { get; set; }

        public Category Category { get; set; }
    }
}
